remote_theme: pages-themes/minimal@v0.2.0
title: Deyaa Mohammed
logo: /assets/img/me.png
description: Tech enthusiast, software tester, and avid gamer. Driven by a passion for technology and a commitment to delivering exceptional software solutions.
show_downloads: false
